### ISSUE TITLE
allocating and reading 8 bytes to `Anemometer_buff[]`

### ISSUE THREAD

**Issue by kbhse** [philippedc/Arduino-ESP8266-RS485-MODBUS-Anemometer#1]
Why are you allocating and reading 8 bytes to `Anemometer_buff[]`? The Response Frame only has 7 bytes.
Reading 8 bytes limits the response time to > 1 second, perhaps hitting the `Serial.setTimeout()` default of 1 second on the 8th byte.
Your test output to the serial monitor is reading 7 bytes.
You can check the return value of `RS485Serial.readBytes(anemometerBuff, 8)` which will return the number of bytes placed in the buffer (7).

**Comment by philippedc** [comment]
Hi John, many thanks for your comment. I will test 7 bytes as soon as possible.

**Comment by kbhse** [comment]
Thanks Philip, and thanks for making this resource available. It was very helpful for setting up my RS485 anemometer and wind direction sensors.

**Comment by philippedc** [comment]
You're welcome. I'm myself a beginner, and I can learn so much from others who share their ideas that I must do the same, by helpful reciprocity :)

**Comment by philippedc** [comment]
Hi John, I made the 8 bytes replacement to 7 bytes and it works much quickly! v3.5 of the .ino file reflects this change.
Thanks

**Comment by kbhse** [comment]
Thanks Philip.
